export interface PortfolioItem {
  id: string;
  title: string;
  category: "single" | "carousel" | "video";
  type: "image" | "carousel" | "video";
  mediaUrl: string;
  slides?: string[];
  aspectRatio: "square" | "portrait" | "video";
  tags: string[];
}

export const PORTFOLIO_ITEMS: PortfolioItem[] = [
  // ── CAROUSELS ──
  {
    id: "carousel-1",
    title: "Veto Power Fitness - Carousel Series",
    category: "carousel",
    type: "carousel",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852653/Split_1_4.png",
    slides: [
      "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852653/Split_1_4.png",
      "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852652/Split_2_1.png",
      "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852651/Split_3_1.png",
      "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852651/Split_4_1.png",
      "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852650/Split_5_1.png",
      "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852650/Split_6_1.png",
    ],
    aspectRatio: "portrait",
    tags: ["Carousel", "Fitness", "Branding"],
  },
  {
    id: "carousel-2",
    title: "Brand & Social Strategy Carousel",
    category: "carousel",
    type: "carousel",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852659/Split_1_1.png",
    slides: [
      "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852659/Split_1_1.png",
      "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852658/Split_2.png",
      "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852657/Split_3.png",
      "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852658/Split_4.png",
      "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852656/Split_5.png",
    ],
    aspectRatio: "portrait",
    tags: ["Carousel", "Educational", "Growth"],
  },

  // ── VIDEOS & REELS ──
  {
    id: "video-1",
    title: "Motion Creative Ad 1",
    category: "video",
    type: "video",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/video/upload/v1788852669/make_full_video_ratio_prop.mp4",
    aspectRatio: "video",
    tags: ["Video Ad", "Motion Design"],
  },
  {
    id: "video-2",
    title: "Brand Motion Reel",
    category: "video",
    type: "video",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/video/upload/v1788852672/79-_1.mp4",
    aspectRatio: "video",
    tags: ["Reels", "Social Media"],
  },
  {
    id: "video-3",
    title: "SA Creative Motion Spot",
    category: "video",
    type: "video",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/video/upload/v1788852669/SA_creative_2_1.mp4",
    aspectRatio: "video",
    tags: ["Ad Creative", "Branding"],
  },
  {
    id: "video-4",
    title: "Magic Visual Motion Showcase",
    category: "video",
    type: "video",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/video/upload/v1788852668/Refined_Video_Prompt___A_magic_2.mp4",
    aspectRatio: "video",
    tags: ["Motion Design", "Visual Effects"],
  },
  {
    id: "video-5",
    title: "High Performance Ad Video",
    category: "video",
    type: "video",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/video/upload/v1788852667/make_sec_video_for_ads_to_ru_3.mp4",
    aspectRatio: "video",
    tags: ["Ad Performance", "Meta Ads"],
  },
  {
    id: "video-6",
    title: "Icon Gym Promo Video",
    category: "video",
    type: "video",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/video/upload/v1788852660/Icon_s_Gym_9.mp4",
    aspectRatio: "video",
    tags: ["Fitness", "Promo Video"],
  },
  {
    id: "video-7",
    title: "Veto Power Fitness Hub Reel",
    category: "video",
    type: "video",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/video/upload/v1788852660/VETOPOWER_FITNESS_HUB.mp4",
    aspectRatio: "video",
    tags: ["Gym", "Reel"],
  },

  // ── SINGLE CREATIVES ──
  {
    id: "single-1",
    title: "Google Ads vs Meta Ads",
    category: "single",
    type: "image",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852654/Google_Ads_vs_Meta_Ads_3.png",
    aspectRatio: "portrait",
    tags: ["Infographic", "Marketing"],
  },
  {
    id: "single-2",
    title: "Top 7 Data Science Skills 2026",
    category: "single",
    type: "image",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852664/TOP_7_DATA_SCIENCE_SKILLS_THAT_WILL_GET_YOU_HIRED_IN_2026_2.png",
    aspectRatio: "portrait",
    tags: ["Tech Graphic", "Education"],
  },
  {
    id: "single-3",
    title: "Top AI Websites for Students & Creators",
    category: "single",
    type: "image",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852662/Top_AI_Websites_for_Students_Creators_2.png",
    aspectRatio: "portrait",
    tags: ["AI", "Creators"],
  },
  {
    id: "single-4",
    title: "How Small Businesses Can Use AI",
    category: "single",
    type: "image",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852664/How_Small_Businesses_Can_Use_AI.png",
    aspectRatio: "portrait",
    tags: ["AI Graphic", "Business"],
  },
  {
    id: "single-5",
    title: "5 Reasons to Choose Veto Power Gym (#3)",
    category: "single",
    type: "image",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852667/5_Reasons_to_Choose_VETO_POWER_Gym_3.png",
    aspectRatio: "portrait",
    tags: ["Gym Poster", "Fitness"],
  },
  {
    id: "single-6",
    title: "5 Reasons to Choose Veto Power Gym (#5)",
    category: "single",
    type: "image",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852665/5_Reasons_to_Choose_VETO_POWER_Gym_5.png",
    aspectRatio: "portrait",
    tags: ["Fitness", "Branding"],
  },
  {
    id: "single-7",
    title: "5 Reasons to Choose Veto Power Gym (#7)",
    category: "single",
    type: "image",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852664/5_Reasons_to_Choose_VETO_POWER_Gym_7.png",
    aspectRatio: "portrait",
    tags: ["Gym Ad", "Creatives"],
  },
  {
    id: "single-8",
    title: "Why is it Called Veto Power?",
    category: "single",
    type: "image",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852649/WHY_IS_IT_CALLED_VETO_POWER.png",
    aspectRatio: "portrait",
    tags: ["Brand Story", "Design"],
  },
  {
    id: "single-9",
    title: "The Strongest Hero Is the One Who Never Quits",
    category: "single",
    type: "image",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852654/The_Strongest_Hero_Is_the_One_Who_Never_Quits..png",
    aspectRatio: "portrait",
    tags: ["Motivation", "Poster"],
  },
  {
    id: "single-10",
    title: "Strength is Earned — One Rep at a Time",
    category: "single",
    type: "image",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852449/STRENGTH_IS_EARNED._ONE_REP_AT_A_TIME..png",
    aspectRatio: "portrait",
    tags: ["Fitness", "Social Media"],
  },
  {
    id: "single-11",
    title: "Join Now Fitness Campaign",
    category: "single",
    type: "image",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852447/JOIN_NOW.png",
    aspectRatio: "portrait",
    tags: ["Call to Action", "Promo"],
  },
  {
    id: "single-12",
    title: "Creative Banner Concept",
    category: "single",
    type: "image",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852663/Untitled_design_14.png",
    aspectRatio: "square",
    tags: ["Banner", "Social Media"],
  },
  {
    id: "single-13",
    title: "Brand Aesthetic Poster 17629",
    category: "single",
    type: "image",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852670/1762939480475.avif",
    aspectRatio: "portrait",
    tags: ["Aesthetic", "Visual Design"],
  },
  {
    id: "single-14",
    title: "Creative Concept 176294",
    category: "single",
    type: "image",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852670/1762941473293.avif",
    aspectRatio: "portrait",
    tags: ["Graphic", "Branding"],
  },
  {
    id: "single-15",
    title: "Social Creative Concept A",
    category: "single",
    type: "image",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852655/Add_a_heading_5.png",
    aspectRatio: "square",
    tags: ["Social Media", "Design"],
  },
  {
    id: "single-16",
    title: "Social Creative Concept B",
    category: "single",
    type: "image",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852649/Add_a_heading_4.png",
    aspectRatio: "square",
    tags: ["Social Media", "Poster"],
  },
  {
    id: "single-17",
    title: "I Don't Have Time - Fitness Motivation",
    category: "single",
    type: "image",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852649/I_Don_t_Have_Time_1.png",
    aspectRatio: "portrait",
    tags: ["Motivation", "Fitness"],
  },
  {
    id: "single-18",
    title: "Creative Social Showcase 35",
    category: "single",
    type: "image",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852446/Untitled_design_35.png",
    aspectRatio: "square",
    tags: ["Creative", "Design"],
  },
  {
    id: "single-19",
    title: "Brand Photo Showcase",
    category: "single",
    type: "image",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852446/WhatsApp_Image_2026-07-21_at_9.49.10_PM_1.jpg",
    aspectRatio: "portrait",
    tags: ["Photography", "Branding"],
  },
  {
    id: "single-20",
    title: "Strength Edition 3 Graphic",
    category: "single",
    type: "image",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852446/STRENGTH_IS_EARNED._ONE_REP_AT_A_TIME._3.png",
    aspectRatio: "portrait",
    tags: ["Fitness", "Graphic"],
  },
  {
    id: "single-21",
    title: "Social Design Concept 37",
    category: "single",
    type: "image",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852445/Untitled_design_37.png",
    aspectRatio: "square",
    tags: ["Social Media"],
  },
  {
    id: "single-22",
    title: "Social Design Concept 40",
    category: "single",
    type: "image",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852445/Untitled_design_40.png",
    aspectRatio: "square",
    tags: ["Social Media"],
  },
  {
    id: "single-23",
    title: "Social Design Concept 51",
    category: "single",
    type: "image",
    mediaUrl: "https://res.cloudinary.com/ylaq4tml/image/upload/v1788852445/Untitled_design_51.png",
    aspectRatio: "square",
    tags: ["Social Media"],
  },
];
